% Precompute and package hyperparameter expressions into vector form
function cached = ComputeCachedLikelihoodTerms( kappa, nu, sigsq )

cached = [ ...
    0 ...
    kappa ...
    nu ...
    sigsq ...
    nu * sigsq ...
    -gammaln(nu/2) + (1/2)*log(kappa) + (nu/2)*log(nu*sigsq)];

cached = cast(cached, 'single');
end

